//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emp_be.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string StaffNumber { get; set; }
        public string Email { get; set; }
    }
}
